name: Build APK

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Patch ABI
        run: |
          sed -i 's/include("arm64-v8a", "x86_64")/include("armeabi-v7a")/' LSFG-Android-Application/app/build.gradle.kts
          sed -i 's/include("arm64-v8a")/include("armeabi-v7a")/' LSFG-Android-Application/app/build.gradle.kts

      - name: Patch C++
        run: |
          sed -i 's/static_cast<void \*>(&(s.swap_surface))/reinterpret_cast<void*>((uintptr_t)(s.swap_surface))/' LSFG-Android-Application/app/src/main/cpp/lsfg_render_loop.cpp
          sed -i 's/static_cast<void \*>(&(s.swap_swapchain))/reinterpret_cast<void*>((uintptr_t)(s.swap_swapchain))/' LSFG-Android-Application/app/src/main/cpp/lsfg_render_loop.cpp

      - name: Build
        run: |
          cd LSFG-Android-Application
          chmod +x gradlew
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: LSFG-Android-Application/app/build/outputs/apk/debug/*.apk
