name: Build APK

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Patch ABI
        run: |
          sed -i 's/arm64-v8a/armeabi-v7a/g' LSFG-Android-Application/app/build.gradle.kts

      - name: Bruteforce Patch C++
        run: |
          sed -i '651s/.*/        LOGI("createSwapchain: surface=%p", (void*)0);/' LSFG-Android-Application/app/src/main/cpp/lsfg_render_loop.cpp
          sed -i '753s/.*/        LOGI("createSwapchain: swapchain=%p", (void*)0);/' LSFG-Android-Application/app/src/main/cpp/lsfg_render_loop.cpp

      - name: Build
        run: |
          cd LSFG-Android-Application
          chmod +x gradlew
          ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: LSFG-Android-Application/app/build/outputs/apk/debug/*.apk
